name: Bearer PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  rule_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Bearer
        uses: bearer/bearer-action@v2
        with:
          diff: true
          with:
          skip-path: 'index.html'
